### ISSUE TITLE
join

### ISSUE THREAD

**Issue by TangYutian** [lanunion-editor/lanunion-editor.github.io#1]
How about your project ?

**Comment by weearc** [comment]
Invitation has been sent.

**Comment by weearc** [comment]
work will be started in three days

**Comment by TangYutian** [comment]
received, but I am not sure about how to start the work .

**Comment by weearc** [comment]
clone the repo ：workspace backup ，and make sure you have create a new working branch，then remove the md files in the post folder(I can't remember) and working with new md files generated by Hugo (you can download this tool and see how it works). DO NOT WORK IN THE MASTER BRANCH.

**Comment by Thorean** [comment]
How about the new working branch?
